# Note: the production environment is given to us automatically when we deploy to heroku
#  
#
#
#

staging:
  adapter: postgresql
  encoding: unicode
  database: picbounce_staging
  pool: 5
  
development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: picbounce_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: picbounce_test
  pool: 5

analytics:
  adapter: mysql
  database: picbounce_analytics
  encoding: utf8
  username: picbounce
  password: cadet4cognizance
  host: svn.clxsrv.com
  
