staging:
  adapter: postgresql
  encoding: unicode
  database: picbounce_staging
  pool: 5
  username: brad
  
development:
  adapter: postgresql
  encoding: unicode
  database: picbounce_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: picbounce_test
  pool: 5
  username: postgres
  password:

analytics:
  adapter: mysql
  database: picbounce_analytics
  encoding: utf8
  username: picbounce
  password: cadet4cognizance
  host: svn.clxsrv.com

