exp:
  adapter: postgresql
  encoding: unicode
  database: pb_exp
  pool: 5
  username: brad
  password:

development:
  adapter: postgresql
  encoding: unicode
  database: picbounce_development
  pool: 5
  username: 
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: picbounce_test
  pool: 5
  username: postgres
  password:
