development:
  access_key_id: AKIAIIZEL3OLHCBIZBBQ
  secret_access_key: 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

test:
  access_key_id: AKIAIIZEL3OLHCBIZBBQ
  secret_access_key: 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

production:
  access_key_id: AKIAIIZEL3OLHCBIZBBQ
  secret_access_key: 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
