#!/usr/bin/env ruby
# This command will automatically be run when you run "rails" with Rails 3 gems installed from the root of your application.

APP_PATH = File.expand_path('../../config/application',  __FILE__)
require File.expand_path('../../config/boot',  __FILE__)

#added this line as a workaround for the bug desribed here: https://github.com/rails/rails/issues/1866
#This allows rails plugin install to work
#This should be removed once we update rails and/or rake
module Commands; end

require 'rails/commands'
